### PR TITLE
No 2-letter words for DQA names

### PR DESCRIPTION
**Pull request by theturtle32**
Filtered the dictionary to exclude all words shorter than three characters.

Actual (node.js) filtering code was:
```javascript
const fs = require('fs');

data = JSON.parse(fs.readFileSync('./words.json').toString('utf8'));

Object.keys(data).forEach(key => {
    let values = data[key].
        flatMap(value => {
            if (value.match(/jihad/)) return '';
            return value.
                replace(/[^a-z-]/g, '-').
                split('-').
                filter(word => word.length >= 3).
                join('-');
        }).
        filter(value => value.length > 0);

    // values = values.sort((a,b) => a.length - b.length);

    data[key] = values;

    // values.forEach(word => console.log(word));
    // values = values.flatMap(word => word.split('-'));
    // console.dir(values.reduce((last, word) => {
    //     last[word.length] = (last[word.length] || 0) + 1;
    //     return last;
    // }, {}))

    console.log(`${key} – ${data[key].length}`);
});

fs.writeFileSync('filtered-words.json', JSON.stringify(data));

```

### CODE REVIEW

**Comment by bkeroackdsc** [comment]
@theturtle32 Can you also update the word counts in the [README](https://github.com/dollarshaveclub/acyl/tree/master/data#contents) please?

**Comment by theturtle32** [comment]
> @theturtle32 Can you also update the word counts in the [README](https://github.com/dollarshaveclub/acyl/tree/master/data#contents) please?

Done!

**Review by esterlinej — APPROVED** [review]
LGTM

**Review by bkeroackdsc — APPROVED** [review]

**Comment by esterlinej** [comment]
Will run a Canary Deployment will merge once confirmed successful and deploy the other half.

**Pull request merged**
